const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { generateAIResponse } = require('../../handlers/aiCore');
const prisma = require('../../utils/database');

module.exports = {
    data: new SlashCommandBuilder()
        .setName("quote")
        .setDescription("Dapatkan motivasi, kutipan bijak, atau ayat harian dari AI."),
    name: "quote",
    description: "Dapatkan motivasi, kutipan bijak, atau ayat harian dari AI.",
    category: "ai",
    async execute(interaction) {
        await interaction.deferReply();
        
        let aiConfig = null;
        if (interaction.guild) {
            aiConfig = await prisma.aiSettings.findUnique({
                where: { guildId: interaction.guild.id }
            }).catch(() => null);
        }

        if (aiConfig && !aiConfig.quoteEnabled) {
            return interaction.editReply("⚠️ Fitur Quote/Motivasi dinonaktifkan di server ini.");
        }

        try {
            const prompt = [
                { role: "system", content: "Kamu adalah pemberi motivasi yang bijak. Berikan SATU kutipan filosofis, kutipan tokoh terkenal, atau ayat, lalu berikan 1-2 kalimat refleksi/penjelasan singkat tentang maknanya untuk kehidupan sehari-hari." },
                { role: "user", content: "Tolong berikan aku motivasi hari ini." }
            ];

            const response = await generateAIResponse(prompt, 0.8);

            const embed = new EmbedBuilder()
                .setColor("#FFE259") // Warna keemasan / terang
                .setTitle("✨ Inspirasi Hari Ini")
                .setDescription(response)
                .setFooter({ text: "Generated by Bytebot AI" })
                .setTimestamp();

            await interaction.editReply({ embeds: [embed] });
            
        } catch (error) {
            console.error(error);
            await interaction.editReply("Terjadi kesalahan saat mencoba memanggil AI untuk mendapatkan motivasi.");
        }
    },
};
